site_name: tuppi.ovh

markdown_extensions:
- plantuml_markdown:
    server: http://www.plantuml.com/plantuml

nav:
  - Home: 'index.md'
  - Simple Data Server: '!include ./github/data-server-stm32/mkdocs.yml'
  - Smart Home: 'smart_stats.md'

plugins:
  - monorepo
